###############################################
# LINUX

BINFILE ?= u2w_passwd

BINFILE := ${BINFILE}${DEBUGEXT}

MINCFLAGS = -D_GNU_SOURCE -DUNIX -DWITH_MALLOC -D_LARGEFILE64_SOURCE -DU2W_PASSWD

TESTCFLAGS := ""

MINLIBS = -lcrypt

include Makefile.u2w
